version: '3.5'
services:
  admin:
    image: xuxueli/xxl-job-admin:2.2.0
    restart: always
    hostname: admin
    container_name: xxl_job
    ports:
      - 28888:8080
    volumes:
      - "./tmp:/data/applogs"
      - "./py_data:/data/py_data"
    network_mode: "bridge"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://192.168.10.140:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=zhpoc0818'

  xxl-job-executor:
    build:
      context: ./
    restart: always
    ports:
      - 8089:8089
      - 9999:9999
    container_name: xxl-job-executor
    environment:
      PARAMS: "--xxl.job.admin.addresses=http://192.168.10.140:28888/xxl-job-admin --server.port=8089 --xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler"
    image: kobedocker24/xxl-job-executor-sample-springboot:2.2.0
    volumes:
      - "./py_data:/data/py_data"
    depends_on:
      - admin
    network_mode: "bridge"
