global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.exmail.qq.com:465'
  smtp_from: 'suxiuzhen@matrixtime.com'
  smtp_auth_username: 'suxiuzhen@matrixtime.com'
  smtp_auth_password: 'kYKvQQkBzxsHHjQf'  # 注意不是邮件密码
  smtp_require_tls: false
  smtp_hello: 'qq.com'
templates:
    - '/etc/alertmanager/*.tmpl'
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: 'suxiuzhen@matrixtime.com'
      html: '{{ template "email.to.html" . }}'
      headers: { Subject: "[WARN]告警" }
      send_resolved: true