global:
  scrape_interval: 60s
  evaluation_interval: 60s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "192.168.10.140:9093" ]
rule_files:
  - "/etc/prometheus/rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ "192.168.10.140:9090" ]
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ "192.168.10.140:9100" ]
        labels:
          instance: 192.168.10.140
      - targets: [ "192.168.10.33:9100" ]
        labels:
          instance: 192.168.10.33
  - job_name: 'alertmanager'
    static_configs:
      - targets: [ "192.168.10.140:9093" ]
  - job_name: 'mysql'
    static_configs:
      - targets: [ '192.168.10.140:9104' ]
        labels:
          instance: db
  - job_name: 'nvidia'
    static_configs:
      - targets: [ "192.168.10.140:9835" ]
        labels:
          instance: 192.168.10.140-gpu
      - targets: [ "192.168.10.33:9835" ]
        labels:
          instance: 192.168.10.33-gpu