global:
  scrape_interval: 60s
  evaluation_interval: 60s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ "192.168.10.140:9090" ]
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ "192.168.10.140:9100" ]
        labels:
          instance: 192.168.10.140
      - targets: [ "192.168.10.33:9100" ]
        labels:
          instance: 192.168.10.33

